# Example IDs from Schep et al.: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE66386

species:
  saccharomyces_cerevisiae:
    samples:
      - data_unstranded
    bowtie2_index: "/s/project/multispecies/fungi_code/atac/debug/schep/data/index/index"
    effective_genome_size: 12157105
    fasta: "/s/project/multispecies/fungi_code/atac/debug/schep/data/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa"
    folds: "/data/nasif12/home_if12/rehm/shorkie/atac-seq-pipeline/config/cerevisiae_8_individual/fold_0.json"

  schizosaccharomyces_pombe:
    samples:
      - SRR1822148
      - SRR1822149
      - SRR1822150
      - SRR1822151
      - SRR1822152
    bowtie2_index: "/s/project/multispecies/inter_glm/schizosaccharomyces_pombe/genome/schPom"
    effective_genome_size: 12591209
    fasta: "/s/project/multispecies/inter_glm/schizosaccharomyces_pombe/genome/schPom.fa"
    folds: "/data/nasif12/home_if12/greissl/atac-seq-pipeline/config/folds_pombe.json"

adapter_seq: "CTGTCTCTTATACACATCT" # Nextera adapter sequence
