# Example IDs from Schep et al.: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE66386

species:
  saccharomyces_cerevisiae:
    samples:
      - GSM1621323
      - GSM1621324
      - GSM1621325
      - GSM1621326
      - GSM1621327
      - GSM1621328
      - GSM1621329
      - GSM1621330
      - GSM1621331
      - GSM1621332
    bowtie2_index: "/s/project/multispecies/fungi_code/atac/debug/schep/data/index/index"
    effective_genome_size: 12157105
    fasta: "/s/project/multispecies/fungi_code/atac/debug/schep/data/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa"
    folds: "/data/nasif12/home_if12/rehm/shorkie/atac-seq-pipeline/config/cerevisiae_8_individual/fold_0.json"

  schizosaccharomyces_pombe:
    samples:
      - SRR1822148
      - SRR1822149
      - SRR1822150
      - SRR1822151
      - SRR1822152
    bowtie2_index: "/s/project/multispecies/fungi_code/atac/data/chrom_bp_pipeline/pombe/input_files/index/index"
    effective_genome_size: 12591209
    fasta: ":/s/project/multispecies/fungi_code/atac/data/chrom_bp_pipeline/pombe/input_files/ASM294v3_right_chroms.fna"
    folds: "/data/nasif12/home_if12/rehm/shorkie/atac-seq-pipeline/config/pombe_individual_folds/fold_0.json"
    
        
  candida_albicans:
    samples:
      - SRR12487669
      - SRR12487670
      - SRR12487671
    bowtie2_index: "/s/project/multispecies/fungi_code/atac/data/chrom_bp_pipeline/c_albicans/data/input_data/index/index"
    effective_genome_size: 14282666
    fasta: "/s/project/multispecies/fungi_code/atac/data/chrom_bp_pipeline/c_albicans/data/input_data/GCF_000182965.3_ASM18296v3_genomic.fna"
    folds: "/data/nasif12/home_if12/rehm/shorkie/atac-seq-pipeline/config/calbicans_individual_folds/fold_3.json"
adapter_seq: "CTGTCTCTTATACACATCT" # Nextera adapter sequence
