# Example IDs from Schep et al.: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE66386

species:
  saccharomyces_cerevisiae:
    samples:
      - SRR1822137
      - SRR1822138
      - SRR1822139
      - SRR1822140
      - SRR1822141
      - SRR1822142
      - SRR1822143
      - SRR1822144
      - SRR1822145
      - SRR1822146
      - SRR1822147
    bowtie2_index: "/s/project/multispecies/inter_glm/saccharomyces_cerevisiae/genome/sacCer3"
    effective_genome_size: 12157105
    fasta: "/s/project/multispecies/inter_glm/saccharomyces_cerevisiae/genome/sacCer3.fa"
    folds: "/data/nasif12/home_if12/greissl/atac-seq-pipeline/config/folds_yeast.json"

adapter_seq: "CTGTCTCTTATACACATCT" # Nextera adapter sequence
